language: php

sudo: true

php:
  - 7.2
  - 7.3

before_install:
  - composer self-update
  - mongo test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

install:
  - composer update

script:
  - composer phpunit
  - composer phpcs

cache:
  directories:
    - $HOME/.composer/cache
