language: php

env:
  global:
    - DRIVER_VERSION=1.5.3

sudo: true

services:
  - mongodb

php:
  - 7.2
  - 7.3

before_install:
  - composer self-update
  - mongo test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - pecl install -f mongodb-${DRIVER_VERSION}

install:
  - composer update

script:
  - composer phpunit
  - composer phpcs

cache:
  directories:
    - $HOME/.composer/cache
